#!/usr/bin/env python
# coding=utf-8
# Created by sharp.gan at 2016-08-09
import argparse
import datetime
import os
import sys

import core.common


class Header():
    announcement = 'Above automatically generated by github.com/supersu097/EZcode4CLI'
    def header4bash(self):
        return """#!/usr/bin/env bash
# Created by sharp.gan at {0}
# {1}

""".format(datetime.date.today(), self.announcement)

    def header4py(self):
        return """#!/usr/bin/env python3
# coding=utf-8
# Created by sharp.gan at {0}
# {1}

if __name__ == '__main__':
""".format(datetime.date.today(), self.announcement)


class Misc():
    def writeto(self, content, filename):
        with open(filename, 'w+') as tmp:
            tmp.write(content)

    def suffix_check(self, suffix):
        tool = core.common.Toolbox()
        if suffix not in ['sh', 'py']:
            tool.red_print("Error: The file suffix you passed is '.%s' that \n"
                           "don't need to be a executable script,now "
                           "only support .sh and .py file\n" % suffix)
            sys.exit(1)
        elif os.path.isfile(args.filename):
            tool.red_print("Error: The file of '%s' you wanna touching already"
                           " existed!\n" % args.filename)
            sys.exit(1)


def main(filename):
    suffix = os.path.splitext(filename)[1][1:]
    Misc().suffix_check(suffix)
    if suffix == 'py':
        Misc().writeto(Header().header4py(), filename)
    elif suffix == 'sh':
        Misc().writeto(Header().header4bash(), filename)
    os.system('chmod u+x ' + filename)
    os.system('vim ' + filename)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Help you init header such as '
                    'shebang when you create a script')

    parser.add_argument(
        'filename',
        help='the script file you wanna create')
    args = parser.parse_args()
    main(args.filename)
